#pragma once
#include <unordered_map>
#include <string>

inline std::unordered_map<std::string, std::string> get_embedded_libs() {
    std::unordered_map<std::string, std::string> libs;
    libs["logger.nx"] = "fn info(msg)\n    set t = date.now()\n    set entry = \"[\" + t + \"] [INFO] \" + msg\n    out cli.green(entry)\n    io.append(\"app.log\", entry + \"\\n\")\nend\nfn warn(msg)\n    set t = date.now()\n    set entry = \"[\" + t + \"] [WARN] \" + msg\n    out cli.yellow(entry)\n    io.append(\"app.log\", entry + \"\\n\")\nend\nfn error(msg)\n    set t = date.now()\n    set entry = \"[\" + t + \"] [ERROR] \" + msg\n    out cli.red(entry)\n    io.append(\"app.log\", entry + \"\\n\")\nend\nfn clear_logs()\n    io.write(\"app.log\", \"\")\n    out \"Logs cleared.\"\nend\n";
    libs["fs.nx"] = "fn find_files(directory, extension)\n    out \"Searching \" + directory + \" for *\" + extension + \"...\"\n    set all_files = io.list(directory)\n    set count = 0\n    set results = io.glob(directory + \"/**/*\" + extension)\n    return results\nend\nfn backup_config(config_path, backup_dir)\n    if io.exists(config_path)\n        set timestamp = date.fmt(\"%Y%m%d_%H%M%S\")\n        set name = io.base(config_path)\n        set target = backup_dir + \"/\" + name + \".\" + timestamp + \".bak\"\n        if io.exists(backup_dir)\n            io.copy(config_path, target)\n            out \"Backup successful: \" + target\n            return target\n        else\n            out \"Error: Backup directory does not exist\"\n            return 0\n        end\n    else\n        out \"Error: Source config not found\"\n        return 0\n    end\nend\nfn clean_temp_files(directory, max_age_days)\n    out \"Cleaning temp files in \" + directory\n    set files = io.list(directory)\n    return files\nend\n";
    libs["json_db.nx"] = "fn init_db(db_name)\n    set path = db_name + \".json\"\n    if io.exists(path)\n        out \"DB \" + db_name + \" loaded.\"\n        return 1\n    else\n        io.write(path, \"{}\")\n        out \"DB \" + db_name + \" created.\"\n        return 1\n    end\nend\nfn db_set(db_name, key, value)\n    set path = db_name + \".json\"\n    set data = json.load(path)\n    set updated = json.set(data, key, value)\n    json.save(path, updated)\n    out \"Setting \" + key + \" in \" + db_name\nend\nfn db_get(db_name, key)\n    set path = db_name + \".json\"\n    set data = json.load(path)\n    set val = json.get(data, key)\n    return val\nend\n";
    libs["http_client.nx"] = "fn get_data(url)\n    out \"Fetching JSON from: \" + url\n    set response = net.get_json(url)\n    return response\nend\nfn post_json(url, data_map)\n    out \"Sending POST to: \" + url\n    set payload = json.str(data_map)\n    set response = net.post(url, payload)\n    return response\nend\nfn check_endpoint(url)\n    set status = net.ping(url)\n    if status == 1\n        out \"Endpoint \" + url + \" is UP\"\n        return 1\n    else\n        out \"Endpoint \" + url + \" is DOWN\"\n        return 0\n    end\nend\n";
    libs["nx_suite.nx"] = "fn crawl(url, depth)\n    out \"Crawling: \" + url + \" at depth \" + depth\n    set html = net.get(url)\n    return html\nend\nfn tokenize_raw(code)\n    out \"Tokenizing source...\"\n    set t = str.split(code, \" \")\n    return t\nend\nfn draw_rect(x, y, w, h, color)\n    out \"Drawing Rect at \" + x + \",\" + y + \" Color: \" + color\n    gui.draw_rect(x, y, w, h, color)\nend\nfn draw_rect_outline(x, y, w, h, color)\n    gui.draw_rect_outline(x, y, w, h, color)\nend\nfn draw_circle(x, y, r, color)\n    gui.draw_circle(x, y, r, color)\nend\nfn draw_circle_outline(x, y, r, color)\n    gui.draw_circle_outline(x, y, r, color)\nend\nfn draw_text(x, y, text, color)\n    gui.draw_text(x, y, text, color)\nend\n";
    libs["ssl.nx"] = "fn get(url)\n    return net.get(url)\nend\n\nfn post(url, data)\n    return net.post(url, data)\nend\n\nfn download(url, filepath)\n    return net.download(url, filepath)\nend\n";
    libs["utils.nx"] = "fn welcome(name)\n    out \"Welcome to the Nexus ecosystem, \" + name + \"!\"\n    out \"Current Time: \" + date.now()\nend\nfn calculate_area(radius)\n    set pi = 3.14159\n    set area = pi * math.pow(radius, 2)\n    return area\nend\nfn is_even(n)\n    set mod = n % 2\n    if mod == 0\n        return 1\n    else\n        return 0\n    end\nend\n";
    return libs;
}
